# Locators
# Contact_link = "link:Contact"
First_name = "id:FirstName"
last_name = "id:LastName"
Company_name = "//input[@id='Company']"
Email = "css:input[id='Email']"
phone_no = "css:#Phone"
HQ_Location_Country = "name:HQ_Location_Country__c"
Industry = "name:Industry__c"
Comments = "id:Next_Step_Comments__c"
Checkbox = "xpath://label[text()='I agree to receive communications from Infogix']/following-sibling::div[2]/label"
Submit_button = "Submit"
